### ISSUE TITLE
Isn't this another case of Wix's DIY syndrome?

### ISSUE THREAD

**Issue by orrsella** [wix/sokoban#1]
Honest question – doesn't [Docker Compose](https://docs.docker.com/compose/), [Docker Swarm](https://docs.docker.com/swarm/), [Docker Machine](https://docs.docker.com/machine/), [Docker Toolbox](https://github.com/docker/toolbox), [Crane](https://github.com/michaelsauter/crane), [Shipyard](https://github.com/shipyard/shipyard), or [Helios](https://github.com/spotify/helios) – among *sooooo* many others – already solve this problem? Isn't this another case of Wix's *Do It Yourself* syndrome?

**Comment by electricmonk** [comment]
Well, yeah.
We could've researched the subject, learn the relevant tools and make some decisions - maybe also regarding the production deployment and orchestration tools.

However, we needed something *now*.

The idea behind Sokoban is a dead-simple orchestration tool _directed at E2E tests_. It's open-source mainly so that us Node.js people can reuse it.

Eventually I hope we come to use a proper orchestration tool for our production environment - at which points the E2Es should definitely exercise this orchestrator.
